### ISSUE TITLE
Watson Discovery News Data Dump

### ISSUE THREAD

**Issue by several27** [IBM/watson-discovery-news-alerting#38]
Is it possible to query discovery news for all historically added news (download data dump)? I know it would be possible to do with an API call (https://gateway.watsonplatform.net/discovery/api/v1/environments/system/collections/news/query), but with limitations of 50 results per query that'd be very expensive.

**Comment by stevemar** [comment]
I'm not sure, I wouldn't think so?

You can ask Watson Discovery related questions over here: https://developer.ibm.com/answers/smartspace/watson/index.html

**Comment by stevemar** [comment]
Additionally, you can ask here, too: https://stackoverflow.com/questions/tagged/watson-discovery

**Comment by several27** [comment]
Thanks will ask there 👍
